### ISSUE TITLE
Why did rc-v0.6.3 deploy to qa not restart libqa.

### ISSUE THREAD

**Issue by dkinzer** [tulibraries/tul_cob#1036]
The first time we deployed rc-v0.6.4 to libqa it failed with the following error:

```
RUNNING HANDLER [cob : always run deploy tasks] ***********************************************************
failed: [libqa] (item=assets:clobber) => {"changed": true, "cmd": "bash -lc 'RAILS_ENV=production bundle exec rake assets:clobber'", "delta": "0:00:01.952099", "end": "2019-03-06 16:20:19.840979", "item": "assets:clobber", "msg": "non-zero return code", "rc": 1, "start": "2019-03-06 16:20:17.888880", "stderr": "I, [2019-03-06T16:20:19.825109 #16034]  INFO -- : Removed /var/www/tul_cob/public/assets\nWebpacker requires Node.js >= 6.14.4 and you are using 6.12.3\nPlease upgrade Node.js https://nodejs.org/en/download/", "stderr_lines": ["I, [2019-03-06T16:20:19.825109 #16034]  INFO -- : Removed /var/www/tul_cob/public/assets", "Webpacker requires Node.js >= 6.14.4 and you are using 6.12.3", "Please upgrade Node.js https://nodejs.org/en/download/"], "stdout": "", "stdout_lines": []}
failed: [libqa] (item=assets:precompile) => {"changed": true, "cmd": "bash -lc 'RAILS_ENV=production bundle exec rake assets:precompile'", "delta": "0:00:05.840884", "end": "2019-03-06 16:20:26.029091", "item": "assets:precompile", "msg": "non-zero return code", "rc": 1, "start": "2019-03-06 16:20:20.188207", "stderr": "I, [2019-03-06T16:20:24.163002 #16240]  I
```
Then I reran the deployment and it seemed to deploy correctly but on further inspection it was noted passenger failed to restart.

After restarting manually things seem good but from error above there is a chance assets were not created as expected and this is a false good deploymet.

**Comment by bibliotechy** [comment]
@dkinzer So, what happened is this:

The "deploy tasks" ( i.e. clobber, precompile) and  restarting passenger are "handlers", meaning they do not always run on their own but are triggered when tasks make a change. For example, in this task:
https://github.com/tulibraries/tul_cob_playbook/blob/master/roles/cob/tasks/install-app.yml#L9-L20 
whenever the git checkout actually pulls down changes, it adds the `restart passenger app` and  `deploy tasks` to what is essentially an in memory queue in the running Ansible process. 

When an ansible playbook gets to the end of a section, it looks at the handlers queue runs any tasks that have been added.  

So, in this case, the first time you ran the deploy, git checkout changed the code, and `deploy tasks` and `restart passenger app` were added to ther queue. The section completed, so ansible started running handlers in the queue, but errored out on the first handler. The ansible process terminated at that point, so the in memory queue went away.

When you ran the deploy a second time, the git checkout did not cause any code to change because that work had already been done by the previous failed deploy. So the `deploy tasks` and `restart passenger app` handlers were never added to the queue, because nothing had changed.

Essentially, we are not handling failed deploys in the way we ought to...which is that we should have a rollback mechanism. That brings us back to the last known working state.

**Comment by cmharlow** [comment]
Breaking into 2 tickets based on pairing:

- [Pin node.js install version in playbook to 6.16.0](https://github.com/tulibraries/tul_cob_playbook/issues/41)
- [Create rollback mechanism for Ansible failed deploys, along with relevant monitoring & logging of Ansible plays (moving to grittyOps since effects all ansible resources)](https://github.com/tulibraries/grittyOps/issues/40)

Based off the above, i think this ticket is okay to close.

**Comment by dkinzer** [comment]
OK @cmharlow thanks.  I'm closing this ticket now that we know what caused the issue and have these other tickets to follow up on.
