### ISSUE TITLE
Handling tul_cob / Alma + Primo API pain points

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/tul_cob#1050]
- [x] adjust timeouts
  - [x] Primo calls
  - [x] Alma calls
- [ ] Emails & Text messages perform via batch
- [ ] isolate Alma API clients for bifurcating monitoring & isolating downtime issues
- [ ] do some group profiling work to see if other parts of app are causing slowdowns
- [ ] discuss external API or lookup state + caching techniques (a goal of the upcoming authorities integration work)
- [ ] Where possible do concurrent calls.

**Comment by cmharlow** [comment]
@dkinzer what can we do to get this work moving again?

**Comment by dkinzer** [comment]
@cmharlow for starters... someone needs to review and hopefully merge this or throw it back with change requests:
- [ ] https://github.com/tulibraries/alma_rb/pull/40

Then we need to get this up to production and see if it makes a difference.  I think it's been out of mind  because we haven't had an outage in a while now.

**Comment by cmharlow** [comment]
@dkinzer already done this AM as part of my monday open tickets / PRs / issues review. What next

**Comment by cmharlow** [comment]
Dropping this here in case we can address it too https://app.honeybadger.io/projects/56250/faults/46664771#notice-summary

**Comment by dkinzer** [comment]
The next bit is getting this pushed to to production... then I think we can put this to rest for a while.
